apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pro-app
  template:
    metadata:
      labels:
        app: pro-app
    spec:
      containers:
        - name: pro-app
          image: ahmed277/pro-app:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5